services:

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: fortex-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  postgres:
    image: postgres:16
    container_name: fortex-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - fortex-postgres-data:/var/lib/postgresql/data

volumes:
  fortex-postgres-data:
