; SENTINEL-X : firmware ESP8266 (NodeMCU v2)
; Compiler : pio run        Flasher : pio run -t upload        Moniteur : pio device monitor
[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
extra_scripts = pre:build_epoch.py
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    adafruit/Adafruit SSD1306@^2.5.10
    adafruit/Adafruit GFX Library@^1.11.9
